# Header
menu:
  App Store: "https://itunes.apple.com/us/app/delightful-trovebox-photo/id878230610?ls=1&mt=8"
  About Delighftul: "http://www.getdelightfulapp.com"
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/delightfulapp/delightful"
#  weibo: "#"
#  rss: "/atom.xml"
#  facebook: "#"
  # google: "#"
  twitter: "https://twitter.com/delightfulapp"
  # linkedin: "#"
  rss: "/atom.xml"
rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

#你的头像
avatar: "http://www.getdelightfulapp.com/img/delightful-icon-small.png"
#是否开启分享
share: false
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: false 
#是否开启云标签
tagcloud: false
